In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.random.randint(1,100,(6,6))
print(x)

[[83 84 45 19  1 49]
 [97 90 26 65 73 11]
 [54 87 87  7 51 87]
 [40 93 19 95  7 56]
 [ 5 58 50 50 23  3]
 [68 95 52 14 45 32]]


In [4]:
x[0]

array([83, 84, 45, 19,  1, 49])

In [3]:
print(x[0,0])


83


In [5]:
print(x[2,3])

7


In [6]:
x[:,0] #first column

array([83, 97, 54, 40,  5, 68])

In [8]:
x[:,4]

array([ 1, 73, 51,  7, 23, 45])

In [9]:
x[:,-2]

array([ 1, 73, 51,  7, 23, 45])

In [10]:
y = ([1,2,3,4],[6,4,2,2],[2,3,4,3],[1,2,4,1])
x = np.array(y)
print(x)

[[1 2 3 4]
 [6 4 2 2]
 [2 3 4 3]
 [1 2 4 1]]


In [10]:
print(x[1: , 0:3])

[[97 90 26]
 [54 87 87]
 [40 93 19]
 [ 5 58 50]
 [68 95 52]]
